services:
  app:
    image: "majestic-cup-app"
    build:
      context: .
    container_name: majestic-cup-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - SPRING_DATA_MONGODB_URI=mongodb://${DB_AUTH_USERNAME}:${DB_AUTH_PASSWORD}@db:27017/${DB_NAME}?authSource=admin
    networks:
      - app-network
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_AUTH_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_AUTH_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network :
    driver: bridge

